add clusterNetwork_CIDR and serviceNetwork variables
ocp-power-automation/ocp4-playbooks pull request #130
Opened 2021-08-21 06:45 UTC by schabrolles

Add the possibility to choose clusterNetwork and service Network CIDR.
(which is mandatory for implementing multicluster networking with RHACM and submariner)

2021-08-23 07:13 UTC, Prajyot-Parab approved these changes
/lgtm

2021-08-23 09:28 UTC, Prajyot-Parab requested changes

2021-08-23 09:28 UTC, Prajyot-Parab commented on playbooks/roles/ocp-config/defaults/main/main.yaml
> +serviceNetwork: 172.30.0.0/16
Change var names to `cluster_network_cidr` and `service_network` (at all places)

2021-08-23 11:50 UTC, Prajyot-Parab approved these changes, later dismissed
/lgtm

2021-09-02 16:15 UTC, yussufsh commented on playbooks/roles/ocp-config/defaults/main/main.yaml
> +service_network: 172.30.0.0/16
Could you please add a newline at the EOF?

2021-09-02 17:00 UTC, yussufsh approved these changes
/lgtm

2021-09-02 17:02 UTC, bpradipt approved these changes
/lgtm

2021-09-03 05:41 UTC, merged