Upgrading restricted network OCP cluster
ocp-power-automation/ocp4-playbooks pull request #176
Opened 2022-11-14 15:15 UTC by sajauddin

Signed-off-by: sajauddin <sajauddin.mohammad@ibm.com>

2022-11-14 16:44 UTC, sajauddin commented
/assign @yussufsh

2023-01-29 08:32 UTC, yussufsh commented
@sajauddin  please check the review comments.

2023-01-30 14:38 UTC, yussufsh requested changes

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/defaults/main.yaml
> +restricted_network_upgrade: "false"
Can we have this type as boolean?

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/README.md
> +| architecture               | no       | ""                | Architecture of the cluster eg. ppc64le               |
With empty default value suggest this should be a `Required` variable.
Can you set the default column to `ppc64le` (remove from comment) so that it is an optional variable.

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/defaults/main.yaml
> +architecture: ""
Default value should be `ppc64le`.

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/tasks/main.yaml
> +  - restricted_network_upgrade != "true"
nit: 
```suggestion
  - not restricted_network_upgrade
```

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/tasks/main.yaml
> +  - restricted_network_upgrade != "true"
```suggestion
  - not restricted_network_upgrade
```

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/tasks/main.yaml
> +    - restricted_network_upgrade == "true"
```suggestion
    - restricted_network_upgrade
```

2023-01-30 14:38 UTC, yussufsh commented on playbooks/roles/ocp-upgrade/tasks/main.yaml
> +    - architecture != ""
No need to check if default is set and optional.

2023-01-31 08:47 UTC, yussufsh approved these changes
/approve
/cc @Prajyot-Parab @pravin-dsilva

2023-01-31 09:30 UTC, Prajyot-Parab approved these changes
/approve

2023-01-31 13:40 UTC, pravin-dsilva commented
/approve

2023-02-01 04:18 UTC, Prajyot-Parab approved these changes
/lgtm

2023-02-01 04:19 UTC, merged